spring:
  config:
    import:
      - classpath:/application-secret.yml

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create # create update none
    defer-datasource-initialization: true
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  redis: # redis 설정 (로컬)
    host: 127.0.0.1
    port: 6379

cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    s3:
      folder :
        folderName1: user
        folderName2: roadmap
        folderName3: post
      bucket: tily-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false