create table alarm_tb (
       id bigint generated by default as identity,
        created_date timestamp,
        updated_date timestamp,
        is_checked boolean,
        comment_id bigint,
        receiver_id bigint,
        til_id bigint,
        primary key (id)
)

create table comment_tb (
       id bigint generated by default as identity,
        created_date timestamp,
        updated_date timestamp,
        content varchar(255),
        til_id bigint,
        writer_id bigint,
        primary key (id)
)

create table reference_tb (
       id bigint generated by default as identity,
        category varchar(255) not null,
        link TEXT not null,
        step_id bigint,
        primary key (id)
)


create table roadmap_tb (
       id bigint generated by default as identity,
        created_date timestamp,
        updated_date timestamp,
        category varchar(255) not null,
        code varchar(255),
        current_num bigint,
        description varchar(255),
        image varchar(255),
        is_public boolean,
        is_recruit boolean,
        name varchar(255) not null,
        step_num integer,
        creator_id bigint,
        primary key (id)
)

create table step_tb (
       id bigint generated by default as identity,
        description varchar(255),
        due_date timestamp,
        title varchar(255) not null,
        roadmap_id bigint,
        primary key (id)
)


create table til_tb (
       id bigint generated by default as identity,
        created_date timestamp,
        updated_date timestamp,
        comment_num integer,
        content varchar(255),
        is_personal boolean,
        submit_content varchar(255),
        submit_date timestamp,
        title varchar(255) not null,
        roadmap_id bigint,
        step_id bigint,
        writer_id bigint,
        primary key (id)
)

create table user_roadmap_tb (
       id bigint generated by default as identity,
        created_date timestamp,
        updated_date timestamp,
        content TEXT,
        is_accept boolean,
        progress integer not null,
        role varchar(255) not null,
        roadmap_id bigint,
        user_id bigint,
        primary key (id)
)



create table user_step_tb (
       id bigint generated by default as identity,
        is_submit boolean not null,
        roadmap_id bigint,
        step_id bigint,
        user_id bigint,
        primary key (id)
)

create table user_tb (
       id bigint generated by default as identity,
        created_date timestamp,
        updated_date timestamp,
        email varchar(50) not null,
        image varchar(255),
        name varchar(50) not null,
        password varchar(100) not null,
        role varchar(255),
        primary key (id)
)                             