namespace: default
resources:
  - nginx.yaml
  - mariadb.yaml
  - backend.yaml
  - redis.yaml
  #- ingress.yaml
configMapGenerator:
  - name: nginx
    files:
      - config/default.conf
  - name: init-db
    files:
      - config/init.sql   